Train:
  batch_size: 64
  learning_rate: 0.01
  reg: 0.0002
  epochs: 500
  momentum: 0.9
  debug: True

Model:
  type: TwoLayerNet # SoftmaxRegression or TwoLayerNet
  hidden_size: 256 # only applicable for TwolayerNet